version: "3.8"
services:
  pharmacy-recommendation-redis: # 레디스 서비스 이름 설정
    container_name: pharmacy-recommendation-redis # 컨테이너 명 설정
    build:
      dockerfile: Dockerfile # 도커 파일 명 기입
      context: ./redis # 도커 파일이 위치한 경로 작성
    image: wnsdnjs70/pharmacy-recommendation-redis # 이미지 이름 설정
    ports:
      - "6379:6379" # 레디스가 기본 포트를 6379를 써서 그대로 포워딩
  pharmacy-recommendation-database: # 마리아db 서비스 이름 설정
    container_name: pharmacy-recommendation-database # 컨테이너 명 설정
    build:
      dockerfile: Dockerfile # 도커 파일 명 기입
      context: ./database # 도커 파일이 위치한 경로 작성
    image: wnsdnjs70/pharmacy-recommendation-database # 이미지 이름 설정
    environment:  # DB 접속 키를 노출시키지 않기 위해 환경변수로 설정 후 해당 파일을 gitignore 안에 위치
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:  # mariadb에서 한글이 깨지는걸 막기 위해 local의 config 파일을 참조하기 위해 작성
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306" # DB가 기본 포트를 3306 써서 그대로 포워딩
